#include <iostream> 
using namespace std;
int main(){
    cout<<"Different operators in c++:"<<endl;
    // arithmetic operators
    int a = 10, b = 2;

    cout<<" The sum is: "<<(a+b)<<endl;
    cout<<" The difference is: "<<(a-b)<<endl;
    cout<<" The product is: "<<(a*b)<<endl;
    cout<<" The division is: "<<(a/b)<<endl;
    cout<<" The modulo is: "<<(a%b)<<endl;

// logical operators AND/OR/NOT
int p = 2,q = 5;
cout<<(p>q) || (p<q) ;//OR OPERATOR
}